### ISSUE TITLE
Support markdown-it plugin

### ISSUE THREAD

**Issue by pisces312** [vnotex/vnote#165]
I have seen many plugins for markdown-it render.
https://markdown-it.github.io/

Is it possible to support them? This will bring some existing powerful features without making VNote too complex and meet different requirements easily.

**Comment by tamlok** [comment]
Actually VNote now uses several markdown-it plugins. It requires code change to load the plugin and different plugins may have different configs. It is hard to abstract a universal interface to the user. Another problem is too many plugins may make Markdown messy and less portable.

So I think we could come back in the future.

**Comment by Belphemur** [comment]
Sorry to bump this issue. But would it be possible to have a system where the user could load themselves the needed plugins ?

Like a specific folder in the configuration that would be use to load markdown-it plugins.
This way, you won't have to do the support yourself. Also, this would surely create a community around building "plugins" for Vnote for Markdown-it.

Just a thought, since Markdown-it plugins are basic javascript.

**Comment by tamlok** [comment]
It is free to rewrite any Javascript parts of VNote from 3.0. You could add any scripts to VNote now.
