### ISSUE TITLE
Will spelling check supported?

### ISSUE THREAD

**Issue by jizusun** [vnotex/vnote#214]
Maybe the spelling check for English is heavily needed, and later support for Chinese?
Or is any workaround to do spelling check in vnote?

Thanks!

**Comment by smilingsun** [comment]
Ok, for now, the workaround is that I open it in SublimeText with spelling check enabled 😄

**Comment by tamlok** [comment]
Spell check and auto-completion will be supported! I need to find out an open source implemention of spell check.

Thanks!

**Comment by Symbian9** [comment]
@tamlok, Please, use  try find C++ implementation.

P.S.: No need such solution in JavaScript. VNote already has too much JavaScript modules.

**Comment by dtzWill** [comment]
Friendly ping! This would be a great addition, and hopefully not too difficult given the existing solutions that many projects use successfully (hopefully any integration challenges have long since been sorted out).

Is there a preference between the above two approaches, by VNote developers or as seen in use elsewhere?  I'd be willing to help test and maybe light dev work if that'd be useful.  If any approach is attempted/explored, please share your findings/thoughts! :)

**Comment by tamlok** [comment]
@dtzWill Hi, I perfer the Hunspell solution. However I am now too busy at work to develop VNote, so there is no timeline for this for now.

**Comment by DutchPete** [comment]
@tamlok : has your work situation changed at all so that this issue could be worked on?

**Comment by ddark008** [comment]
You can use spellcheck lib from telegram:
https://github.com/desktop-app/lib_spellcheck

**Comment by tamlok** [comment]
Spell check is now supported now, guys! Sorry for the delay.
